defaults:
  order_by: tuple()
  engine: MergeTree
tables:
  - source: store.site
  - source: store.site_address
  - source: store.site_contact
  - source: store.site_format
  - source: store.site_info


