services:
  crm_updater:
    build:
      context: ../..
      dockerfile: crm_generator/Dockerfile
    image: crm_generator:latest
    container_name: crm_updater
    restart: unless-stopped
    env_file:
      - .env
    command: python -m service.crm_generator.updater.crm_updater
    networks:
      - traefik_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  traefik_network:
    external: true
